### ISSUE TITLE
Document the best practices for Agent comments

### ISSUE THREAD

**Issue by mhasself** [simonsobs/ocs#13]
Agent code is special in that it plugs into the OCS system in a particular way.  Some functions represent Tasks, some represent Processes... and the Agent itself will be invoked according to OCS idioms.  We should standardize the way in which these elements are communicated to developers / users.

Processes & Tasks: I have seen (somewhere) a nice approach to marking these functions properly, and documenting their parameter dictionary.  Let's formalize that as an example in the docs.

Agents: as suggested by @BrianJKoopman, the Agent preamble comments should include an example site_config block.  What else should (almost-always) be in there?

We could start by finding places in the code where this has been done well -- then copy that info into the docs as a prescription.  (Then go in and update all the existing Agents to be compliant.)

**Comment by BrianJKoopman** [comment]
This is a long one, but I wanted to explain my thoughts behind the proposed changes, and I think this will improve our docs considerably from the perspective of a user trying to write OCS clients.

After a discussion with a user the other day I want to come back to this issue that's been open for quite a while. The discussion related to the difficulty of figuring out from the docs what arguments can be passed to a task or process, particularly within the Lakeshore 372 Agent.

The Lakeshore 372 Agent is an interesting one because it's one of our first, but also because it somewhat relies on knowledge of the driver code, which is perhaps not reference sufficiently within the Agent code. Putting that aside, I think there are some elements to how we document tasks and processes that could use some improvement, as they've confused even me at times.

## session
When writing an Agent, each Task and Process is written as a method of the Agent class. Each task/process definition is defined with the arguments `(self, session, params=None)`. Here's the definition of the `init` task with its docstring (actual method replaced with `pass`):
```
    def init_lakeshore_task(self, session, params=None):
        """init_lakeshore_task(params=None)
        Perform first time setup of the Lakeshore 372 communication.
        Args:
            params (dict): Parameters dictionary for passing parameters to
                task.
        Parameters:
            auto_acquire (bool, optional): Default is False. Starts data
                acquisition after initialization if True.
            acq_params (dict, optional): Params to pass to acq process if
                auto_acquire is True.
        """
        pass
```

`session` itself is somewhat confusing as a documented argument in the context of documenting tasks/processes because the user never really has to care about passing it, it's handled internal to OCS. It's created within the Agent, and passed as the only positional argument to the task/process launcher when calling either `deferToThread`: 
https://github.com/simonsobs/ocs/blob/eb05e11848f287119c9e911239271b90c29b0e2d/ocs/ocs_agent.py#L592
or `deferLater`:
https://github.com/simonsobs/ocs/blob/eb05e11848f287119c9e911239271b90c29b0e2d/ocs/ocs_agent.py#L595

As such, I think _every_ task/process documented should do what the `init_lakeshore_task` docstring is doing, and override the method signature to exclude `session` from the docstring as it shows up in Sphinx, i.e. when looking on readthedocs the user will only see ` init_lakeshore_task(params=None)`.

## params
`params` is confusing in a different way. I think this comes down to how they're passed in a "Basic Client" vs in a "Matched Client". I'll use the fake-data agent as an example here, as that's easy to demo.

### Usage
A Basic Client (does anyone actually use these anymore?) requires `params` to be passed as a dict, i.e.:
```
    yield ops['delay_task'].start(params={"delay": 1})
    yield ops['delay_task'].wait()
```

A Matched Client requires `params` to be passed individually as keyword arguments, i.e.:
```
therm_client.delay_task.start(delay=1)
therm_client.delay_task.wait()
```
or using the alternative shortcut:
```
therm_client.delay_task(delay=1)
```

Doing the opposite in either case will yield differing results. In the case of the Basic Client you'll get a TypeError, when start() gets an unexpected keyword, which will crash the client. Passing a `params` dict to a MatchedClient is perhaps more subtle in that it will pass just fine, but won't actually apply as you might expect if you're expecting behavior to match the basic client. This is even more of a pitfall if an argument isn't required and has some default set, i.e.
```
therm_client.delay_task(params={'delay': 1})
```
This looks like we're setting the delay to 1 second, but instead the Matched Client doesn't know how to handle this and will use the default delay of 5 seconds.

### Documentation
Part of what was initially awkward with documenting the parameters for a task/process was the fact that basic clients takes a params dict the way it does. I thought using the usual way of documenting arguments in Sphinx, where each argument gets an entry like:
```
        Args:
            delay (float): Time to wait before returning, in seconds.
                Defaults to 5.
            succeed (bool): Whether to return success or not.
                Defaults to True.
```
would be misleading to someone reading the docs and expecting it to behave like any other method they're used to reading the docs for in Python. For example, they'd see `delay_task(delay=5, success=True)` (or the above block) in the docs and use it as such `delay_task(delay=1, success=False)`, when they needed to actually do `delay_task(params={'delay': 1, 'success': False})`. This led to only having:
```
        Args:
            params (dict): Parameters dictionary for passing parameters to
                task.
```
Typically with a description of what keys and values should be used. `set_heater_range` might be a better example of the attempt at being more descriptive:
```
        :param params: dict with 'range', 'wait' keys
        :type params: dict
        range - the heater range value to change to
        wait - time in seconds after changing the heater value to wait, allows
               the servo to adjust to the new heater range, typical value of
               ~600 seconds
```
Ultimately I think this is what's difficult to work out for the users I had the discussion with that sparked this post. Possible values of 'range' in this instance aren't listed (with the assumption the user would look at the [driver code docs](https://socs.readthedocs.io/en/develop/agents/lakeshore372.html#socs.Lakeshore.Lakeshore372.Heater.set_heater_range) that provide those details.)

### autodoc
We've been using autodoc, specifically autoclass, to build the task/process documentation. This presents some subtle ambiguities:
* It's not clear which methods in the Agent class are tasks and which are processes. Some methods try to state this as the first line in their docstring, but that is rare. autodoc alphabetizing this list also likely mixes these up, if they are separated in the source, which I'm not sure is done anywhere anyway.
* The names of the method and the name registered for the operation within OCS might differ. This is relatively uncommon. Looking through all the socs Agents, only 17 of the 71 registered tasks differ in method name and registered ocs name. But these differences are often small and, in my opinion, unnecessary. For example, `init_lakeshore_task` as a method name, and `init_lakeshore` as the registered OCS Task name. (This one seems to have propagated to almost every other Agent that requires an "init" type task.) There's an attempt to fix this with the signature overriding, for example in the 372 Agent with `start_acq()` being declared as just the registered `acq()`, but this doesn't actually work when rendered in Sphinx:
https://github.com/simonsobs/socs/blob/ff6b66afdf672357b04dd1b5e6cf20a925f90e0b/agents/lakeshore372/LS372_agent.py#L191
* Process `stop` methods are documented, but to the user in an OCS client, that method is hidden effectively by the process itself, as you only need to call `client.process.stop()` on the process. They won't be calling `client.process.stop_methods_name()`, to give a generic example.

## Proposal
Matched Clients are the most common interaction method, and should be the priority for how things are documented.

1. Arguments should _always_ be documented as if they are keyword arguments to the operation caller, i.e.
```
        Args:
            delay (float): Time to wait before returning, in seconds.
                Defaults to 5.
            succeed (bool): Whether to return success or not.
                Defaults to True.
```
**NOT**
```
        Args:
            params (dict): parameter dictionary with keys 'delay' and 'succeed'.
```

2. The method signature should _always_ be overridden to remove `session` and `params` and to include all possible params as keyword arguments with their default values shown, i.e.
```
    def delay_task(self, session, params={}):
        """delay_task(delay=5, succeed=True)

        Task that will take the requested number of seconds to complete.
        ...
```
resulting in Sphinx docs that render to:
```
delay_task(delay=5, succeed=True)
```
**NOT**
```
    def delay_task(self, session, params={}):
        """Task that will take the requested number of seconds to complete.
        ...
```
which renders in Sphinx to:
```
delay_task(session, params={})
```
3. Examples for each task/process should be encouraged when a task/process has arguments, using the standard Example(s) header, i.e.:
```
        Examples:
            Some examples of calling the init task::

                client.init(auto_acquire=True)
                client.init(auto_acquire=True, acq_params={'sample_heater': True})
```
This will render into a code block that can easily be copy + pasted from.

4. These details for how to properly document an Agent's tasks/processes should be captured in the Development guide along with other details that are already well established, like "include ocs-site-config file and docker-compose examples".

### Questions
* Related to 2. above -- how do we consider params that are required, but have no default coded in? We shouldn't document them as positional arguments, as they can't be used that way and need their argument name supplied when called with `.start()`.

### Other Changes to Consider
* Match the behavior of how params are passed to Basic and Matched Clients. The proposal here would be to make Basic Clients accept params like a Matched Client does, i.e. as direct keyword arguments, not with the single `params` dict.
* Protect the keyword argument 'params' in Matched Clients. As pointed out above, it's a potentially confusing argument name if it's misunderstood how params are passed to a client.
* Split tasks and processes into separate sections in the documentation.
    * This would involve using `automethod` and hand listing all available tasks/processes, which is increased work for Agent authors, but would allow for clearer docs on the user end.
    * Would we still want the sections used now that are generally titled "Agent API" that autoclass the entire class? I think probably not, as the actual class isn't used by users, and arguments to the class aren't important except for at the bottom of an actual Agent file when the Agent is constructed.
    * This gives some ability to fine tune what shows up, i.e. we could not list the stop methods for processes. (Though a similar thing could be accomplished if they were marked as private methods with a leading underscore and autoclass is still used throughout.)
    * To give an example:
```
Tasks
-----

.. automethod:: agents.lakeshore372.LS372_agent.LS372_Agent.init_lakeshore_task
    :noindex:
```
* Write more examples of how to interact with tasks/processes in the Clients documentation page. It's there in words (for a matched client anyway), but there's no clear example for how to pass arguments to either client.
